susanghan/cafehub-spring

- build.gradle
- src/main/java/com/cafehub/cafehubspring/CafehubSpringApplication.java
- src/main/java/com/cafehub/cafehubspring/common/BaseTimeEntity.java
- src/main/java/com/cafehub/cafehubspring/common/DefaultResponseDto.java
- src/main/java/com/cafehub/cafehubspring/config/SwaggerConfiguration.java
- src/main/java/com/cafehub/cafehubspring/controller/CafeController.java
- src/main/java/com/cafehub/cafehubspring/domain/Cafe.java
- src/main/java/com/cafehub/cafehubspring/domain/Photo.java
- src/main/java/com/cafehub/cafehubspring/dto/CafeSaveRequestDto.java
- src/main/java/com/cafehub/cafehubspring/dto/CafeSaveResponseDto.java
- src/main/java/com/cafehub/cafehubspring/exception/DefaultExceptionResponseDto.java
- src/main/java/com/cafehub/cafehubspring/repository/CafeRepository.java
- src/main/java/com/cafehub/cafehubspring/repository/PhotoRepository.java
- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- src/main/java/com/cafehub/cafehubspring/service/PhotoService.java
- src/main/resources/application.yml
- close #1
- 폴더 구조화 완료했습니다
- common 폴더
- config 폴더
- controller 폴더
- domain 폴더
- dto 폴더
- exception 폴더
- repository 폴더
- service 폴더
- 기본 기능 구현 사항
- BaseTimeEntity
- DefaultResponseDto
- DefaultExceptionResponseDto
> [Style] 기본적인 폴더 구조 정리

- build.gradle
- src/main/java/com/cafehub/cafehubspring/config/SwaggerConfiguration.java
- src/main/resources/application.yml
- close #14 
- application.yml 수정 완료했습니다.
- MySQL 연동을 위한 환경변수 설정 코드 작성
- SQL 로그 출력을 하기 위한 설정 코드 작성
- 스프링 실행 시 버전 관련 문제를 해결하기 위한 코드 추가 작성
- build.gradle 수정 완료했습니다.
- 스프링 버전 다운그레이드 2.5
- 필요한 dependencies 추가
> [Fix] MySQL 연동을 위한 config 수정

- build.gradle
- src/main/java/com/cafehub/cafehubspring/config/SwaggerConfiguration.java
- close #2 
-  Swagger를 띄우기 위한 SwaggerConfiguration.java 개발을 완료했습니다.
> [Feat] Swagger 띄우기

- src/main/java/com/cafehub/cafehubspring/domain/Photo.java
- src/main/java/com/cafehub/cafehubspring/repository/PhotoRepository.java
- close #4 
- Photo Entity, Photo Repository 구현 완료
> [Feat] Photo Entity, Photo Repository 구현

- build.gradle
- src/main/java/com/cafehub/cafehubspring/config/S3Configuration.java
- src/main/resources/application.yml
- close #5 
- S3 Configuration 구현 완료
> [Feat] S3 Configuration 구현

- src/main/java/com/cafehub/cafehubspring/domain/Cafe.java
- src/main/java/com/cafehub/cafehubspring/repository/CafeRepository.java
- close #3
- Cafe Entity, Cafe Repository 구현 완료
> [Feat] Cafe Entity, Cafe Repository 구현

- src/main/java/com/cafehub/cafehubspring/dto/CafeSaveRequestDto.java
- close #22 
- Cafe Save Request Dto 구현 완료
> [Feat] Cafe 저장 Request DTO

- build.gradle
- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- src/main/resources/application.yml
- close #29 
- 주소로부터 좌표값 구하기 구현 완료
> [Feat] 주소를 이용해 위도, 경도 구하기

- src/main/java/com/cafehub/cafehubspring/service/PhotoService.java
- close #31
- PhotoService에서 S3로 저장할때 `{cafeName}-{cafeId}` 형식으로 폴더명 지정하게 변경
> [Refactor] PhotoService에 사진 저장 로직 변경 사항

- .github/workflows/develop-ci.yml
> [Chore] CI 파이프라인 구축 

- src/main/java/com/cafehub/cafehubspring/exception/CustomExceptionHandler.java
- src/main/java/com/cafehub/cafehubspring/exception/http/NotFoundException.java
- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- src/main/java/com/cafehub/cafehubspring/service/PhotoService.java
- close #33 
- PhotoService 예외처리 구현 완료
> [Refactor] PhotoService 예외처리 구현

- src/main/java/com/cafehub/cafehubspring/domain/Cafe.java
- src/main/java/com/cafehub/cafehubspring/dto/CafeSaveRequestDto.java
- src/main/java/com/cafehub/cafehubspring/repository/CafeRepository.java
- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- close #35 
- CafeService 여러 건 조회 구현 완료
> [Feat] CafeService 여러 건 조회 구현

- .github/ISSUE_TEMPLATE/issue-template.md
- .github/PULL_REQUEST/pull-request-template.md
- close #53 
</br>
- Issue 템플릿화
- Pull request 템플릿화
</br>
- 
</br>
> [Docs] Issue, Pull request 템플릿

- src/main/java/com/cafehub/cafehubspring/domain/Cafe.java
- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- close #55 
</br>
- 위도와 경도 좌표값 데이터 타입 Double로 변경 완료
- 좌표값은 소수점 7자리까지로 변경 완료
</br>
- 
</br>
> [Fix] 좌표값 데이터 타입 변경

- src/main/java/com/cafehub/cafehubspring/service/PhotoService.java
- close #56 
</br>
- File 전송 후 삭제 구현 완료
</br>
- 
</br>
> [Fix] 이미지 S3에 전송 후 로컬에서 해당 파일 삭제 필요

- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- close #60 
</br>
- 카페 데이터 전체 조회 기능 구현 완료
</br>
- 
</br>
> [Feat] 카페 데이터 전체 조회 추가

- src/main/java/com/cafehub/cafehubspring/controller/CafeController.java
- src/main/java/com/cafehub/cafehubspring/dto/CafeFindManyRequestDto.java
- src/main/java/com/cafehub/cafehubspring/dto/CafeFindManyResponseDto.java
- src/main/java/com/cafehub/cafehubspring/dto/CafeFindOneResponseDto.java
- src/main/java/com/cafehub/cafehubspring/repository/CafeRepository.java
- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- close #40 
</br>
- 카페 여러 건 조회하는 cafeMany 컨트롤러 구현 완료
- CafeMany 컨트롤러에서 사용할 CafeFindManyRequestDto, CafeFindManyResponseDto 구현 완료
</br>
- 
</br>
> [Feat] CafeController 카페 여러 건 조회 API 구현

- src/main/java/com/cafehub/cafehubspring/exception/CustomExceptionHandler.java
- close #64 
</br>
- ExceptionHandler 400 에러 수정 완료
</br>
- 
</br>
> [Fix] ExceptionHandler 400 에러 수정

- src/main/java/com/cafehub/cafehubspring/controller/CafeController.java
- src/main/java/com/cafehub/cafehubspring/dto/CafeFindManyRequestDto.java
- close #66 
</br>
- CafeFindManyRequestDto에 NotNull 메세지 수정 완료
- CafeController에 ApiResponse 수정 완료
</br>
- 
</br>
> [Fix] Swagger 관련 문서 수정

- src/main/java/com/cafehub/cafehubspring/domain/Cafe.java
- src/main/java/com/cafehub/cafehubspring/domain/OpeningHours.java
- src/main/java/com/cafehub/cafehubspring/domain/Photo.java
- close #68 
</br>
- 식별자 GenerationType 수정 완료
</br>
- 
</br>
> [Fix] 테이블별 식별자 순서 수정

- src/main/java/com/cafehub/cafehubspring/domain/Photo.java
- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- src/main/java/com/cafehub/cafehubspring/service/PhotoService.java
- src/main/java/com/cafehub/cafehubspring/util/DataInjector.java
- close #38 
</br>
- 데이터 주입 관련 코드 완료
- CafeService에 주입 관련 코드 추가 완료
- PhotoService에 주입관련 코드 추가 완료
- Photo 엔티티에 URL length 1000으로 수정 완료
- URL이 256보다 긴 경우 데이터가 주입이 안되서 수정이 필요했습니다
</br>
- 
</br>
> [Chore] 카페 데이터 주입

- .github/workflows/develop-pull-request-ci.yml
- .github/workflows/develop-push-ci.yml
- .github/workflows/master-ci.yml
- close #70 
</br>
- master 브랜치 CI 파이프라인 구축 완료
- develop 브랜치 CI 파이프라인 추가 구축 및 세분화 완료
</br>
- 
</br>
> [Chore] Action과 Branch마다 CI 파이프라인 세분화

- src/main/java/com/cafehub/cafehubspring/repository/CafeRepository.java
- close #77 
</br>
- findByCoordinates 부분 쿼리 수정 완료
</br>
- 
</br>
> [Fix] findByCoordinates 부분에 쿼리 에러

- src/main/java/com/cafehub/cafehubspring/dto/CafeFindOneResponseDto.java
- close #79 
</br>
- CafeFindOneResponseDto에 위도 경도 반환 추가
</br>
- 
</br>
> [Feat] 단건 조회시 경도 위도 반환

- src/main/java/com/cafehub/cafehubspring/controller/CafeController.java
- src/main/java/com/cafehub/cafehubspring/controller/MemberController.java
- src/main/java/com/cafehub/cafehubspring/domain/Member.java
- src/main/java/com/cafehub/cafehubspring/repository/MemberRepository.java
- src/main/java/com/cafehub/cafehubspring/service/CafeService.java
- src/main/java/com/cafehub/cafehubspring/service/MemberService.java
- close #90 
</br>
- Member
- domain 구현 완료
- repository 구현 완료
- service 구현 완료
- controller 구현 완료
</br>
- 
</br>
> [Feat] 유저 정보 관리 구현

- src/main/java/com/cafehub/cafehubspring/controller/MemberController.java
- close #92 
</br>
- MemberController에 ApiResponse 추가 완료
</br>
- 
</br>
> [Refactor] MemberController에 ApiResponse 추가

- src/main/java/com/cafehub/cafehubspring/common/BaseTimeEntity.java
- src/main/java/com/cafehub/cafehubspring/domain/Member.java
- src/main/java/com/cafehub/cafehubspring/service/MemberService.java
- close #94 
</br>
- Memer 엔티티에 updatedAt 기능 추가 완료
</br>
- 
</br>
> [Feat] 기존 회원일 경우 회원의 접속 기록 업데이트
